version: "3.3"
services:
  ydb:
    image: ydbplatform/local-ydb:24.3.13.12
    restart: always
    ports:
      - "2136:2136"
    hostname: localhost
    environment:
      - YDB_USE_IN_MEMORY_PDISKS=true
      - YDB_ENABLE_COLUMN_TABLES=true
